export const typesUsers = {
  USER_GET: "USER_GET",

  USER_UPDATE_START: "USER_UPDATE_START",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_ERROR: "USER_UPDATE_ERROR",

  USER_DELETE: "USER_DELETE",
};
